runtime: python27
api_version: 1

service: default
threadsafe: true

handlers:
- url: /
  script: main.app

- url: /index\.html
  script: main.app

- url: /static
  static_dir: static

libraries:
- name: ssl
  version: "latest"